name: Building
env:
  TZ: Asia/Shanghai
  CPU: 'sm8150'
  FEIL: 'miao'
  ANDROID_VERSION: 'android16'
  KERNEL_VERSION: '4.14'
  KERNEL_NAME: 'ShirokoNeko'
  KERNELSU_VARIANT: 'SukiSU-Ultra'
  KERNELSU_BRANCH: 'main-susfs'
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ksuver: ${{ steps.ksu_version.outputs.ksuver }}
    steps:
      - name: 最大化建筑空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          swap-size-mb: 8192
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
      
      - name: 安装配置环境依赖
        run: |
          sudo apt update -y
          sudo apt install -y \
            build-essential \
            flex bison \
            dwarves \
            libssl-dev \
            libelf-dev \
            bc \
            python3 \
            python-is-python3 \
            git \
            make \
            cmake \
            zip \
            curl \
            wget \
            gnupg \
            gcc-multilib \
            g++-multilib \
            ccache \
            rsync \
            binutils-aarch64-linux-gnu \
            binutils-arm-linux-gnueabihf
          wget -q https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/android-11.0.0_r3/clang-r383902b.tar.gz
          mkdir -p aosp-clang
          tar -xzf clang-r383902b.tar.gz -C aosp-clang
          rm clang-r383902b.tar.gz
          echo "AOSP_CLANG_PATH=$(pwd)/aosp-clang" >> $GITHUB_ENV
          echo "PATH=$(pwd)/aosp-clang/bin:$PATH" >> $GITHUB_ENV
      - name: 初始化源码仓库
        run: |
          rm -rf kernel_workspace && mkdir kernel_workspace && cd kernel_workspace
          git clone --depth=1 https://github.com/Winkmoon/android_kernel_oneplus_sm8150.git -b 16.0 common
          rm common/android/abi_gki_protected_exports_* || true
          for f in common/scripts/setlocalversion; do
            sed -i 's/ -dirty//g' "$f"
            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$f"
          done
          sed -i 's/ERR_get_error_all(&err_state)/ERR_get_error()/g' common/scripts/extract-cert.c
          sed -i 's/ERR_STATE_file(err_state)/"unknown"/g' common/scripts/extract-cert.c
          sed -i 's/ERR_STATE_line(err_state)/0/g' common/scripts/extract-cert.c
      
      - name: 添加 SukiSU-Ultra
        id: ksu_version
        run: |
          cd kernel_workspace
          curl -LSs "https://raw.githubusercontent.com/Winkmoon/SukiSU-Ultra-R.I.P/main/kernel/setup.sh" | bash -s main-susfs

      
      
      - name: 添加制作名称
        run: |
          cd kernel_workspace
          cd common
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            for f in ./scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ github.event.inputs.kernel_suffix }}\"|" "$f"
            done
          else
            for f in ./scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ env.KERNEL_NAME }}\"|" "$f"
            done
          fi
      
      - name: 构建内核
        run: |
          cd kernel_workspace
          cd common
          
          export ARCH=arm64
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabihf-
          export PATH=$AOSP_CLANG_PATH/bin:$PATH
          export LLVM=1
          export LLVM_IAS=0
          export KCFLAGS="-Wno-error -Wno-deprecated-declarations"
          
          make O=out xinran_test_sm8150_defconfig
          make -j$(nproc --all) O=out \
            CC=clang \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            STRIP=llvm-strip \
            HOSTCC=clang \
            HOSTLD=ld.lld
      
      - name: 克隆 AnyKernel3 并打包
        run: |
          cd kernel_workspace
          cd common
          git clone https://github.com/Winkmoon/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          cd AnyKernel3
          cp ../out/arch/arm64/boot/Image ./Image
          if [ ! -f ./Image ]; then
            exit 1
          fi
            zip -r ../AnyKernel3_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_${{ env.KERNEL_NAME }}.zip ./*
      
      - name: 上传 ZIP 工件
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_ZIP_Artifacts
          path: ${{ github.workspace }}/kernel_workspace/common/*.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      actions: read
      
    steps:
      - name: 下载 ZIP 工件
        uses: actions/download-artifact@v4
        with:
          name: Kernel_ZIP_Artifacts
          path: ./release_zips
      
      - name: 设置环境变量
        run: |
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            FULL_VERSION=${{ format('{0}.118-{1}', env.KERNEL_VERSION, github.event.inputs.kernel_suffix) }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
          else
            FULL_VERSION=${{ format('{0}.118-{1}', env.KERNEL_VERSION, env.KERNEL_NAME) }}
            echo "FULL_VERSION=$FULL_VERSION" >> $GITHUB_ENV
          fi
          TIME="$(TZ='Asia/Shanghai' date +'%y%m%d%H%M%S')"
          TIME_FORM="$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          echo "TIME=$TIME" >> $GITHUB_ENV
          echo "TIME_FORM=$TIME_FORM" >> $GITHUB_ENV
          TAG_HEAD="4.14"
          echo "TAG_HEAD=$TAG_HEAD" >> $GITHUB_ENV
      
      - name: 创建发布
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.TAG_HEAD }}-${{ env.TIME }}"
          name: "${{ env.TAG_HEAD }}-${{ env.FULL_VERSION }}"
          body: |
            ### sm8150内核 | 构建信息
            - 内核版本号: 4.14
            - 编译时间: ${{ env.TIME_FORM }}
          draft: false
          prerelease: false
          files: |
            release_zips/AnyKernel3_*.zip
